# encoding: UTF-8

class Publication < ActiveRecord::Base
  def self.getz
    {
      :id => "1",
      :title => "pelle",
      :pubyear => "2007",
      :pubtype_id => "15",
      :pubtype_sv => "Skräp",
      :pubtype_en => "Trash"
    }
  end

  def self.listz
    [
      {
      :id => "1",
      :title => "pelle",
      :pubyear => "2007",
      :pubtype_id => "15",
      :pubtype_sv => "Skräp",
      :pubtype_en => "Trash"
      },
      {
      :id => "2",
      :title => "pelle",
      :pubyear => "2007",
      :pubtype_id => "15",
      :pubtype_sv => "Skräp",
      :pubtype_en => "Trash"
      },
      {
      :id => "3",
      :title => "pelle",
      :pubyear => "2007",
      :pubtype_id => "15",
      :pubtype_sv => "Skräp",
      :pubtype_en => "Trash"
      }
    ]
  end

  def self.testj
    {
        'modified'=>'2010-10-19T11:49:32Z',
        'pubtypeid'=>5,
        'sourcevolume'=>'23',
        'dbid'=>120917,
        'abstract'=>'Fully conjugated organic molecules, such as the oligo(phenyleneethynylene) (OPE) systems, are of growing interest within the field of molecular electronics, as is the self-assembly of well-defined molecular thin films with predefined functions. The structure and function of such films are intimately related and governed by the structures of their molecular constituents, through the intermolecular interactions and the interactions between the molecules and the substrate, onto which the film is assembled. Here we report on the synthesis of a series of three OPE derivatives, with the general structure phenylethynylene-aryl-ethynylenephenylene-headgroup, and the structural investigation of the self-assembled monolayers (SAMs) formed from them on Au(111) surfaces. The SAMs were characterized by infrared reflection-absorption spectroscopy, spectroscopic ellipsometry, high-resolution X-ray photoemission spectroscopy, and near-edge X-ray absorption fine structure spectroscopy. The effective thickness of the SAMs was observed to decrease as the pi-system of the aryl moiety of the OPE adsorbate was extended perpendicular to its molecular long axis. Changing the aryl moiety from benzene to naphthalene to anthracene resulted in lower molecular surface densities and larger molecular inclination. The average tilt angles for the benzene, naphthalene, and anthracene SAMs were found to be about 30 degrees, 40 degrees, and 42 degrees from the surface normal, respectively. For the largest adsorbate, the anthracene derivative, there is spectroscopic evidence suggesting the existence of nonequivalent binding sites. The differences observed between the SAMs are rationalized in terms of the shape of the adsorbates and the strength of the pi-pi interactions between them.',
        'seotitle'=>'-characterization-of-self-assembled-monolayers-of-oligophenyleneethynylene-derivatives-of-varying-sha',
        'sourceissue'=>'11',
        'sourcepages'=>'6170-6181',
        'pubyear'=>2007,
        'issn'=>'0743-7463',
        'pubid'=>64862,
        'format'=>'text',
        'created'=>'2008-01-08T15:18:53Z',
        'sourcetitle'=>'Langmuir',
        'title'=>'Characterization of self-assembled monolayers of oligo(phenyleneethynylene) derivatives of varying shapes on gold: Effect of laterally extended pi-systems',
        'pubtype_sv'=>'Artikel, refereegranskad vetenskaplig',
        'pubtype_en'=>'Scientific journal article - peer reviewed',
        'pubtype_dcname'=>'Text.Article.Journal.PeerReviewed',
        'pubtype_mapping_sv'=>'5:Artikel, refereegranskad vetenskaplig',
        'pubtype_popular'=>'0',
        'pubtype_peer_reviewed'=>'1',
        'pubtype_mapping_en'=>'5:Scientific journal article - peer reviewed',
        'pubtype_scientific'=>'1',
        'pubtypegroup_en'=>['Articles',
          'Articles and Conference papers',
          'cpl',
          'gup'],
        'pubtypegroup_mapping_en'=>['21:Articles',
          '22:Articles and Conference papers',
          '41:cpl',
          '43:gup'],
        'pubtypegroupid'=>[21,
          22,
          41,
          43],
        'pubtypegroup_sv'=>['Artiklar',
          'Artiklar och konferensbidrag',
          'cpl',
          'gup'],
        'pubtypegroup_mapping_sv'=>['21:Artiklar',
          '22:Artiklar och konferensbidrag',
          '41:cpl',
          '43:gup'],
        'person_mapping'=>['23378:Nilsson, Daniel',
          '105194:Watcharinyanon, S.',
          '22366:Eng, Mattias P.',
          '105195:Li, L. Q.',
          '105196:Moons, E.',
          '105197:Johansson, L. S. O.',
          '105198:Zharnikov, M.',
          '105199:Shaporenko, A.',
          '281:Albinsson, Bo',
          '1244:Mårtensson, Jerker'],
        'person_role_mapping_en'=>['1:Author',
          '1:Author',
          '1:Author',
          '1:Author',
          '1:Author',
          '1:Author',
          '1:Author',
          '1:Author',
          '1:Author',
          '1:Author'],
        'person_role_sv'=>['Författare',
          'Författare',
          'Författare',
          'Författare',
          'Författare',
          'Författare',
          'Författare',
          'Författare',
          'Författare',
          'Författare'],
        'person_listplace'=>['1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10'],
        'person_role_id'=>['1',
          '1',
          '1',
          '1',
          '1',
          '1',
          '1',
          '1',
          '1',
          '1'],
        'person_listplace_mapping'=>['23378:1',
          '105194:2',
          '22366:3',
          '105195:4',
          '105196:5',
          '105197:6',
          '105198:7',
          '105199:8',
          '281:9',
          '1244:10'],
        'person_role_mapping_sv'=>['1:Författare',
          '1:Författare',
          '1:Författare',
          '1:Författare',
          '1:Författare',
          '1:Författare',
          '1:Författare',
          '1:Författare',
          '1:Författare',
          '1:Författare'],
        'person_role_en'=>['Author',
          'Author',
          'Author',
          'Author',
          'Author',
          'Author',
          'Author',
          'Author',
          'Author',
          'Author'],
        'personid_extid_mapping'=>['23378:',
          '105194:',
          '22366:mattiasl',
          '105195:',
          '105196:',
          '105197:',
          '105198:',
          '105199:',
          '281:balb',
          '1244:jerker'],
        'person'=>['Nilsson, Daniel',
          'Watcharinyanon, S.',
          'Eng, Mattias P.',
          'Li, L. Q.',
          'Moons, E.',
          'Johansson, L. S. O.',
          'Zharnikov, M.',
          'Shaporenko, A.',
          'Albinsson, Bo',
          'Mårtensson, Jerker'],
        'person_normal_mapping'=>['23378:Daniel Nilsson',
          '105194:S. Watcharinyanon',
          '22366:Mattias P. Eng',
          '105195:L. Q. Li',
          '105196:E. Moons',
          '105197:L. S. O. Johansson',
          '105198:M. Zharnikov',
          '105199:A. Shaporenko',
          '281:Bo Albinsson',
          '1244:Jerker Mårtensson'],
        'person_id'=>[23378,
          105194,
          22366,
          105195,
          105196,
          105197,
          105198,
          105199,
          281,
          1244],
        'persids'=>['23378',
          '105194',
          '22366',
          '105195',
          '105196',
          '105197',
          '105198',
          '105199',
          '281',
          '1244',
          'mattiasl',
          'balb',
          'jerker'],
        'personid_orcid_mapping'=>['23378:',
          '105194:',
          '22366:',
          '105195:',
          '105196:',
          '105197:',
          '105198:',
          '105199:',
          '281:',
          '1244:'],
        'person_normal'=>['Daniel Nilsson',
          'S. Watcharinyanon',
          'Mattias P. Eng',
          'L. Q. Li',
          'E. Moons',
          'L. S. O. Johansson',
          'M. Zharnikov',
          'A. Shaporenko',
          'Bo Albinsson',
          'Jerker Mårtensson'],
        'person_role_mapping'=>['23378:1',
          '105194:1',
          '22366:1',
          '105195:1',
          '105196:1',
          '105197:1',
          '105198:1',
          '105199:1',
          '281:1',
          '1244:1'],
        'person_extid'=>['mattiasl',
          'balb',
          'jerker'],
        'person_first'=>'Nilsson, Daniel',
        'language_id'=>[2],
        'language_en'=>['English'],
        'language_iso'=>['en'],
        'language_mapping_sv'=>['2:engelska'],
        'language_mapping_iso'=>['2:en'],
        'language_mapping_en'=>['2:English'],
        'language_sv'=>['engelska'],
        'department_start_year_mapping'=>['0:1829',
          '380:2005',
          '804:2006'],
        'top_department_en'=>['External',
          'Department of Chemical and Biological Engineering',
          'Department of Chemical and Biological Engineering'],
        'school_en_name'=>['External',
          'Dummy School',
          'Dummy School'],
        'school_sv_name'=>['Extern',
          'Dummy School',
          'Dummy School'],
        'department_sv'=>['Extern',
          'Institutionen för kemi- och bioteknik, Fysikalisk kemi',
          'Institutionen för kemi- och bioteknik, Organisk kemi'],
        'palasso_katagu_mapping'=>[':',
          ':',
          ':'],
        'department_mapping_sv'=>['0:Extern',
          '380:Institutionen för kemi- och bioteknik, Fysikalisk kemi',
          '804:Institutionen för kemi- och bioteknik, Organisk kemi'],
        'top_department_mapping_sv'=>['0:Extern',
          '369:Institutionen för kemi- och bioteknik',
          '369:Institutionen för kemi- och bioteknik'],
        'department_en'=>['External',
          'Department of Chemical and Biological Engineering, Physical Chemistry',
          'Department of Chemical and Biological Engineering, Organic Chemistry'],
        'dept_palasso_mapping'=>['0:',
          '380:',
          '804:'],
        'top_department_sv'=>['Extern',
          'Institutionen för kemi- och bioteknik',
          'Institutionen för kemi- och bioteknik'],
        'department_school_mapping'=>['0:0',
          '380:58',
          '804:58'],
        'school_mapping_sv'=>['0:Extern',
          '58:Dummy School',
          '58:Dummy School'],
        'top_department_id'=>[0,
          369,
          369],
        'school_mapping_en'=>['0:External',
          '58:Dummy School',
          '58:Dummy School'],
        'department_end_year_mapping'=>['0:',
          '380:',
          '804:'],
        'department_mapping_en'=>['0:External',
          '380:Department of Chemical and Biological Engineering, Physical Chemistry',
          '804:Department of Chemical and Biological Engineering, Organic Chemistry'],
        'dept_katagu_mapping'=>['0:',
          '380:',
          '804:'],
        'schoolid'=>['0',
          '58',
          '58'],
        'start_year'=>1829,
        'department_id'=>[0,
          380,
          804],
        'depts'=>[0,
          380,
          804,
          369,
          369],
        'top_department_mapping_en'=>['0:External',
          '369:Department of Chemical and Biological Engineering',
          '369:Department of Chemical and Biological Engineering'],
        'dep_parentid'=>[369,
          369],
        'department_person_mapping'=>['380:281',
          '804:1244',
          '380:22366',
          '804:23378',
          '0:105194',
          '0:105195',
          '0:105196',
          '0:105197',
          '0:105198',
          '0:105199'],
        'top_department_person_mapping'=>['369:281',
          '369:1244',
          '369:22366',
          '369:23378',
          '0:105194',
          '0:105195',
          '0:105196',
          '0:105197',
          '0:105198',
          '0:105199'],
        'instance_mapping_en'=>['0:UPL-instance',
          '1:Chalmers University of Technology'],
        'instance_abbrev'=>['UPL',
          'Chalmers'],
        'instance_mapping_abbrev'=>['0:UPL',
          '1:Chalmers'],
        'instance_mapping_sv'=>['0:UPL-instans',
          '1:Chalmers tekniska högskola'],
        'instanceid'=>[0,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0],
        'instance_sv_name'=>['UPL-instans',
          'Chalmers tekniska högskola'],
        'instance_en_name'=>['UPL-instance',
          'Chalmers University of Technology'],
        'instance_top_department_mapping'=>['1:369',
          '1:369',
          '1:369',
          '1:369',
          '0:0',
          '0:0',
          '0:0',
          '0:0',
          '0:0',
          '0:0'],
        'instance_department_mapping'=>['1:380',
          '1:804',
          '1:380',
          '1:804',
          '0:0',
          '0:0',
          '0:0',
          '0:0',
          '0:0',
          '0:0'],
        'instance_person_mapping'=>['1:281',
          '1:1244',
          '1:22366',
          '1:23378',
          '0:105194',
          '0:105195',
          '0:105196',
          '0:105197',
          '0:105198',
          '0:105199'],
        'category_mapping_en'=>['1203:Chemical Sciences'],
        'category_type'=>['HSV_LOCAL_12'],
        'category_id'=>[1203],
        'svepid'=>[104],
        'category_path_en'=>['NATURAL SCIENCES|Chemical Sciences'],
        'category_sv'=>['Kemi'],
        'category_path_mapping_en'=>['1203:NATURAL SCIENCES|Chemical Sciences'],
        'category_mapping_type'=>['1203:HSV_LOCAL_12'],
        'category_mapping_svepid'=>['1203:104'],
        'category_path_mapping_sv'=>['1203:NATURVETENSKAP|Kemi'],
        'category_en'=>['Chemical Sciences'],
        'category_path_sv'=>['NATURVETENSKAP|Kemi'],
        'category_mapping_sv'=>['1203:Kemi'],
        'extid_mapping'=>['DOI:10.1021/la0636964',
          'ISI-ID:000246456700047'],
        'extid_name'=>['DOI',
          'ISI-ID'],
        'extid_value'=>['10.1021/la0636964',
          '000246456700047'],
        'timestamp'=>'2013-10-22T11:05:02.691Z'}
  end
end
